# Generated by Django 5.0.3 on 2024-03-21 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='номинал')),
                ('added_date', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('photo', models.ImageField(blank=True, default='coin_photos/default_image.jpg', null=True, upload_to='coin_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('coins', models.ManyToManyField(to='collection_app.coin', verbose_name='Монеты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_app.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection_app.user', verbose_name='Пользователь'),
        ),
    ]
