# Generated by Django 5.0.3 on 2024-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0002_remove_coin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='condition',
            field=models.CharField(choices=[('Плохое', 'Плохое'), ('Среднее', 'Среднее'), ('Отличное', 'Отличное'), ('Не определено', 'Не определено')], default='Не определено', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='photo',
            field=models.ImageField(blank=True, default='collection_app/coin_photos/default_image.jpg', null=True, upload_to='collection_app/coin_photos/'),
        ),
    ]
