# Generated by Django 5.0.3 on 2024-03-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0003_coin_condition_alter_coin_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='photo',
        ),
        migrations.AddField(
            model_name='coin',
            name='photo_obverse',
            field=models.ImageField(blank=True, default='collection_app/coin_photos/default_image.jpg', null=True, upload_to='collection_app/coin_photos/', verbose_name='фото аверс'),
        ),
        migrations.AddField(
            model_name='coin',
            name='photo_reverse',
            field=models.ImageField(blank=True, default='collection_app/coin_photos/default_image.jpg', null=True, upload_to='collection_app/coin_photos/', verbose_name='фото реверс'),
        ),
    ]
