# Generated by Django 5.0.3 on 2024-03-22 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0004_remove_coin_photo_coin_photo_obverse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='coins',
        ),
        migrations.AddField(
            model_name='coin',
            name='collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_app.collection', verbose_name='Коллекция'),
        ),
    ]
