# Generated by Django 5.0.3 on 2024-03-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0007_country_coin_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Состояние')),
            ],
        ),
    ]
