# Generated by Django 5.0.3 on 2024-03-24 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0008_coinstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='condition',
        ),
        migrations.AddField(
            model_name='coin',
            name='coinstate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection_app.coinstate', verbose_name='состояние'),
        ),
    ]
