# Generated by Django 5.0.3 on 2024-03-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0009_remove_coin_condition_coin_coinstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=100, null=True, verbose_name='примерная стоимость'),
        ),
    ]
