# Generated by Django 5.0.3 on 2024-03-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0010_coin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='year_coin',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Год'),
        ),
    ]
