# Generated by Django 5.0.3 on 2024-03-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0011_coin_year_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='year_coin',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Год'),
        ),
    ]
